name: ci

on: [push]

jobs:
  build-frontend:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

  test-scheduler:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./scripts/scheduler

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        make clean
    - name: Lint with pylint
      run: |
        make lint
    - name: Check types with mypy
      run: |
        make mypy
    - name: Test with pytest
      run: |
        make test
